global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using System.Threading.Tasks;
global using System.Text;
global using BolnicaLibrary.Entiteti;
global using BolnicaLibrary.Mapiranja;
global using BolnicaLibrary.DTOs;